wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1673156832.934244
    t:
      1:
      - 1
      - 55
      - 76
      2:
      - 1
      - 55
      - 76
      3:
      - 13
      - 23
      4: 3.7.15
      5: 0.13.7
      8:
      - 5
